### ISSUE TITLE
Version 2 - TypeScript rewrite

### ISSUE THREAD

**Issue by Stanko** [Stanko/animated-scroll-to#24]
This issue will be used as a main thread of communication for the version 2.

We just started, more info coming soon.

## Todo

* [x] Setup TypeScript (module + `window.animateScrollTo`)
* [x] Refactor library
* [x] New method signatures
  * `(y, options)`
  * `([x, y], options)`
  * `(element, options)`
* [x] Diagonal scroll
* [x] Add custom easing to options
* [x] Tests
  * [x] Setup CircleCI
* [x] Fail silently on server
* [x] Two synchronous calls on the same element should cancel each other (they should)
* [ ] Better demo

## Maybe

* [x] ~TBD remove `cancelOnUserAction` (consider it always to be `true`)~ just defaults to true
* [x] `Promise` interface https://github.com/Stanko/animated-scroll-to/issues/23

## Breaking Changes

* New method signatures
* Removed `horizontal` option

**Comment by Stanko** [comment]
Work in progress can be seen on this branch
https://github.com/Stanko/animated-scroll-to/tree/ts

I'll release beta version soon.

**Comment by Stanko** [comment]
Released as 2.0.0 🎉
